### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by bluefire2121** [Paol-imi/muuri-react#1]
README updates:
useState() requires useState to be imported via react.

JSX example may serve some well. 

`  <div class="item" style="display: none">
            <div class="item-content">My item</div>
          </div>`
**class** becomes **className**

**Comment by Paol-imi** [comment]
Do you mean
`import React from 'react'`
`React.useState()`
Instead of
`import React, { useState } from 'react'`
`useState()` ?
