### ISSUE TITLE
`Cannot read property 'child' of null` in prod env 

### ISSUE THREAD

**Issue by sunnyabc789** [Paol-imi/muuri-react#14]
Here is some promble when I run in prod env
but it can run in dev env

`here is my git store`
[my store](https://github.com/sunnyabc789/react-test/tree/test-muuri)
dev script `npm run start`
then you can visit in localhost:8080

build script `npm run build`
then you can find the index.html in /dist/index.html
please open it in browser  it is the prod env and it has the problem

Here is the error in browser console
`react-dom.production.min.js?ca5d:196 TypeError: Cannot read property 'child' of null`

the raw code in your store components/gridComponent.js
` store.itemsOwner = getItemsOwner(vars.grid);`

in the node_modules/muuri-react build/index.js
`function z(e){return e._owner.child`}

when I console.log(e) in prod env
```
$$typeof: Symbol(react.element)
key: null
props: {value: {…}, children: Array(3)}
ref: null
type: {$$typeof: Symbol(react.provider), _context: {…}, displayName: "GridProvider"}
_owner: null
```
_owner is null

when I console.log(e) in dev env
```
$$typeof: Symbol(react.element)
key: null
props: {value: {…}, children: Array(3)}
ref: null
type: {$$typeof: Symbol(react.provider), _context: {…}, displayName: "GridProvider"}
_owner: FiberNode {tag: 0, key: null, elementType: ƒ, type: ƒ, stateNode: null, …}
_store: {validated: false}
_self: null
_source: null
__proto__: Object
```
_owner is FiberNode

I try it in create-react-app too
but after build it has same error

**Comment by Paol-imi** [comment]
Hi sunnyabc789,

Thanks for your accurate feedback it was helpful. To integrate some features of Muuri, with the best user experience and maximum performance, I worked with react internal APIs. I have not really thought that the prod and dev packages could have any differences.

However I just found a solution, it took less pain than expected. I will publish the patch as soon as possible.

- Paolo

**Comment by Paol-imi** [comment]
The patches have been published, now you can update the package. If you have other problems, contact me here.

**Comment by sunnyabc789** [comment]
Thanks for your great encapsulation
