### ISSUE TITLE
how to save the order of the items in kanban example

### ISSUE THREAD

**Issue by juanisimioli** [Paol-imi/muuri-react#19]
Hi! I find this library awesome! A simple question: imagine that I have an app like the kanban example link in your site.
Suppose that after any item movement (from column to column, or inside the same column) I want to update the ORDER of my items in my state.
In your kanban example, you don't save the order of the items. 
Where can I get that data?
I tried to use the values 'fromIndex' and 'toIndex' in file utils.js inside useCallback in line 4, but they are only for movements from column to column, and the data is reliable if I avoid to move other item apart from the one that is beeing dragged.

Hope you can help me!
And congrats again, this library will rock it!

**Comment by Paol-imi** [comment]
Hi juanisimioli

You can sort the items according to their keys ([**docs**](https://paol-imi.github.io/muuri-react/docs/usage/sorting#usage--keys)).
```jsx
<MuuriComponent sort={["2", "1"]}>
   <Item key="1" />
   <Item key="2" />
</MuuriComponent>
```
You can then save these keys by accessing the grid ([**docs**](https://paol-imi.github.io/muuri-react/docs/usage/sorting#store-sort-order-)).

```jsx
const gridRef = useRef();

function saveTheItemKeys() {
   const keys = gridRef.current.getItems.map(item => item.getKey())
   // Save the keys where you want ...
}

<MuuriComponent ref={gridRef}>
   <Item key="1" />
   <Item key="2" />
</MuuriComponent>
```
You can easily apply it after an event, [**here**](https://paol-imi.github.io/muuri-react/docs/usage/muuri) is information on how to use the grid.

```jsx
<MuuriComponent
  onDragEnd={function (item) {
    const grid = item.getGrid();
    const items = grid.getItems();
    const keys = items.map((item) => item.getKey());  // keys: ["1", "2"]
    // Save the keys where you want ...
  }}
>
  <Item key="1" />
  <Item key="2" />
</MuuriComponent>
```

I think you will find it useful to take a look at this [**demo**](https://codesandbox.io/s/muuri-react-sort-959o8)

**Comment by juanisimioli** [comment]
Wow! Now I see documentation is updated and well explained. Great Job!
Thank you!
