### ISSUE TITLE
Next.js Support

### ISSUE THREAD

**Issue by JoshRozin** [Paol-imi/muuri-react#2]
Hey there,

I appreciate all the work you're doing. Muuri needs a React component! Apparently, Next.js's webpack is not compatible with this package. Wondering if you have any plans to support Next.js.

Josh

**Comment by Paol-imi** [comment]
Hi josh, Thank you for appreciation

I know something about Next.js but I'm not an expert, can you provide an example of how you are using it? Is it throwing some errors or doesn't it work at all?

Paolo

**Comment by JoshRozin** [comment]
I added it properly, just like how you did in your demo however seems like the webpack loader for Next.js gives a big error when using this package. Fails to even load the page.

**Comment by Paol-imi** [comment]
Can you share the error that webpack generates?

**Comment by Paol-imi** [comment]
I think I found something.
In the new version I just released, in addition to the new features, I made some patches.

If you try this new version let me know, I hope it works.

**Comment by Paol-imi** [comment]
Solved in 2.0.0.
