### ISSUE TITLE
Error when try to init the application

### ISSUE THREAD

**Issue by m4510** [Paol-imi/muuri-react#20]
ReferenceError: window is not defined
    at /Users/m4510/Documents/next/catadmin_app/node_modules/muuri/dist/muuri.js:218:22
    at /Users/m4510/Documents/next/catadmin_app/node_modules/muuri/dist/muuri.js:19:83
    at Object.<anonymous> (/Users/m4510/Documents/next/catadmin_app/node_modules/muuri/dist/muuri.js:22:2)

any helps ?

**Comment by Paol-imi** [comment]
Are you using server side rendering? If so, you must follow the guide given in the [**documentation**](https://paol-imi.github.io/muuri-react/docs/usage/server-side-rendering/).
