### ISSUE TITLE
Any help appreciated.

### ISSUE THREAD

**Issue by kervinucf** [Paol-imi/muuri-react#21]
I have been struggling with this for a bit. Do you know exactly where the key parameter in the useSend function is converted to a string? I'd like to pass an object through, but I am unsure where the conversion takes place. To be clear this is when you're moving items between grids. 

<img width="306" alt="Screen Shot 2020-04-21 at 12 48 57 AM" src="https://user-images.githubusercontent.com/9199900/79826706-71f6e780-836a-11ea-9ab9-02cdcfe32771.png">

**Comment by Paol-imi** [comment]
The parameter in the onSend function is the key of the react component that is sent. In a react component the key must be a string.

If you are doing this
```jsx
<Component key={myObject} />
```
then you are breaking your application as all the components will have the same "[object object]" key, react should show you a warning.

You should get information of the component that is sent in another way, the [**kanban**](https://codesandbox.io/s/muuri-react-kanban-zmypd) demo may help.
