### ISSUE TITLE
how to refresh dimensions of all items

### ISSUE THREAD

**Issue by juanisimioli** [Paol-imi/muuri-react#22]
Hi! After some changes of height of my items, the layout breaks.
If I resize the browser, the problem solves. 
I read in muuri documentation that there is something like 'grid.refreshItems()' to refresh dimensions of all active item elements.

How can I access that method in muuri-react?

Thanks!

**Comment by Paol-imi** [comment]
You can refresh the items in this [**way**](https://paol-imi.github.io/muuri-react/docs/usage/items-dimensions#dimensions-refresh-).
