### ISSUE TITLE
when drag and drop on filtered items, the app crash

### ISSUE THREAD

**Issue by juanisimioli** [Paol-imi/muuri-react#29]
Hi,
In your example 'Demo Grid', if you filter by any color and you try to drag and drop an item, the app crash and says: "Failed to execute 'animate' on 'Element': Partial keyframes are not supported".
It happens the same to my app. 
Hope you can help, 
Thanks!

**Comment by Paol-imi** [comment]
This is a known [**bug**](https://github.com/haltu/muuri/issues/359) in [**Muuri**](https://github.com/haltu/muuri) in its version 0.8.0, it will be fixed in version 0.9.0.
