### ISSUE TITLE
layout problems when items have a dynamic height

### ISSUE THREAD

**Issue by juanisimioli** [Paol-imi/muuri-react#30]
Hi!
I´m having some layout problems when items have a dynamic height.
I started from your kanban example, and added a button to toggle the height size to items.
Here you can see the code:
https://codesandbox.io/s/muuri-react-kanban-mdmt7?file=/style.css:2702-2721

Changes I made:
-I added a button and state to your index.js to toggle items between two heights.
-I passed that state to the items through props.
-I added a height className with a ternary operator to each item.
-I added useRefresh on each item using the dependecy variable from props.
-I modifified css (removed height and padding from .board-item & .board-item-content)
-I created two classes with different height
If I start to move items between columns (toggling the button between movements), I can see that layout breaks.
Attached are some images.
![b](https://user-images.githubusercontent.com/48897558/81108180-ac29c280-8eee-11ea-805f-474ffd82f158.png)
![a](https://user-images.githubusercontent.com/48897558/81108184-ad5aef80-8eee-11ea-913d-78bace32aea3.png)

What am I doing wrong?

**Comment by Paol-imi** [comment]
Taking a quick look I have not seen any particular problems, I will investigate further to find out if it is a problem with the package.

For now you can use this workaround
```jsx
const App = () => {
   const gridRef = useRef();

   useEffect(() => {
      gridRef.current.refreshItems();
      gridRef.current.layout();
   })

   <MuuriComponent ref={gridRef}>{children}</MuuriComponent>
}
```

**Comment by juanisimioli** [comment]
Thanks for your response. The problem is that I have a lot of MuuriComponent's in my project.
Is there any way to access to the grid reference on the onDragEnd method from muuri? So I can refreshItems and layout only to the grid end?

**Comment by Paol-imi** [comment]
I think it's a problem with the package and I don't think it will work.
If you want to try you can use **item.getGrid()**

You can also access the grids using the **MuuriMap**.

**Comment by Paol-imi** [comment]
I think it's a problem with the package and I don't think it will work.
If you want to try you can use **item.getGrid()**

You can also access the grids using the **MuuriMap**.

**Comment by juanisimioli** [comment]
Nope, it does not work. 
Hope in the future, when onDragEnd triggered , can use refreshItems() and update layout!

**Comment by Paol-imi** [comment]
The latest patch (3.1.5) should have solved the problem, you should now be able to use useRefresh.
