### ISSUE TITLE
alter state and restart muuri items

### ISSUE THREAD

**Issue by juanisimioli** [Paol-imi/muuri-react#32]
Hi!
I am working on a kanban application, and there are some external actions that alter the array state that is used with muuri (add/remove items or columns).
If that state is updated with setState(newArray), muuri start to not working well.
How can I make a muuri restart to understand the new state?

Thanks!

**Comment by Paol-imi** [comment]
I just released a patch that fixes some problems. For now you can try to update the package and see if the problem persists.

**Comment by juanisimioli** [comment]
It worked!
Thanks!
