### ISSUE TITLE
Reset to initial values after moved cards between different grids

### ISSUE THREAD

**Issue by gafernandez87** [Paol-imi/muuri-react#33]
Hello!
I'm working in a Trello-like application and I'm having some issues with the UI.
In order to replicate the problem, I've used the codesandbox for your Kanban demo and just added a RESET button.

The example begins like this
![image](https://user-images.githubusercontent.com/4062648/81872271-d5ca9580-954f-11ea-9047-e4ce3e22d865.png)

Then I move any item from any grid to the other (in this example **Item four** from todo -> working)

![image](https://user-images.githubusercontent.com/4062648/81872339-f2ff6400-954f-11ea-9630-8fc16cfac124.png)

And finally, I clicked reset, expecting to go back to the initial state (with Item four in TODO list) and this happened

![image](https://user-images.githubusercontent.com/4062648/81872400-0ad6e800-9550-11ea-82d5-9b43eeb08785.png)

In order to do this, I am just updating the local state of the component, which has an array of items being displayed in the UI.

From this point, if you try to do anything, the grid goes wild and everything works wrong.

This is the link to the sandbox if you want to try it by yourself https://codesandbox.io/s/muuri-react-kanban-hlfxd?file=/index.js 

Thanks in advance

**Comment by Paol-imi** [comment]
Hi @gafernandez87 

This I think is a muuri-react bug that other users have also encountered. I have just released a patch and tried your example which seems to work.

If you try your app with the updated package and the problem is solved please let me know

**Comment by gafernandez87** [comment]
Hi @Paol-imi ,
That seems to fix the problem!
Thanks for your quick response 👍
