### ISSUE TITLE
dragHandle not working

### ISSUE THREAD

**Issue by k4st0r42** [Paol-imi/muuri-react#34]
This property seems not working? I found it in the documentation

`dragHandle= {'.header'}`

Should I use this instead ?I found it inexamples

`dragStartPredicate={{
                handle:".header"
              }}`

And one other question, when using nested grid, how only select direct child css selector ? And not the drag handles of children ?

Thank you

**Comment by Paol-imi** [comment]
My fault. I developed this package to work with Muuri 0.9.0 (not yet released) and in the documentation I forgot to remove some of these APIs, for now, you have to use *dragStartPredicate*.

For any question regarding the engine you should ask in the issue section of the Muuri repository.
