### ISSUE TITLE
muuri-react doesn't work with later version of muuri

### ISSUE THREAD

**Issue by krsnaa** [Paol-imi/muuri-react#43]
Trying with muuri v. 0.9.x prevents any item from rendering on the screen.
It appears that their display: block CSS property is never set and always stays at display:none.

repro: Take this codesandbox - https://codesandbox.io/s/muuri-react-grid-1czo5 and change muuri version to 0.9 in the package.json file.

**Comment by Paol-imi** [comment]
Hi krsnaa,

This is due to the fact that, in Muuri 0.8.0, "display: none" was used in the style of the items to enable the animation when created. To solve the problem just remove "display: none" from the css style of the items.

**Comment by TheAussieStew** [comment]
Would it be possible for you to update your CodeSandbox examples with the latest Muuri dependency and the correct CSS style? I understand that you're quite busy but this particular issue caused me a lot of grief. Thanks for maintaining this library regardless!

**Comment by Paol-imi** [comment]
[**Sandobox**](https://codesandbox.io/s/muuri-react-grid-forked-di74c?file=/style.css:730-869)

It is a fork of the demo grid, the only change is on the css of the item.

```css
.item {
  /* display: none; */
  width: 100px;
  height: 100px;
  ...
}
```

**Comment by TheAussieStew** [comment]
Yep, it was a very simple change to make once the issue was identified but my suggestion was so that it might save people who are new to Muuri and Muuri-React some time :)

**Comment by Mohamed-Raid** [comment]
> [**Sandobox**](https://codesandbox.io/s/muuri-react-grid-forked-di74c?file=/style.css:730-869)
> 
> It is a fork of the demo grid, the only change is on the css of the item.
> 
> ```css
> .item {
>   /* display: none; */
>   width: 100px;
>   height: 100px;
>   ...
> }
> ```

sandbox example does not exist
