### ISSUE TITLE
Cannot find the __reactInternalInstance$

### ISSUE THREAD

**Issue by XEonAX** [Paol-imi/muuri-react#46]
Hi Paolo,

I'm trying to use muuri-react while I'm learning react.
I keep getting this error `Uncaught Invariant: Invariant failed: Cannot find the __reactInternalInstance$`

https://github.com/Paol-imi/muuri-react/blob/f31c84771cf9fa2d66c12cf5b0dde6d6e090b400/src/controllers/fiberController.ts#L150

While debugging if I change the key to the one that starts with `__reactFiber$` the code doesn't seem to throw any errors.
Without this it blanks out my entire app.
My dependencies are as below, (I have downgraded muuri to 0.8.0 coz I thought 0.9.3 doesnt work well with this)
```
  "dependencies": {
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "@testing-library/jest-dom": "^5.11.5",
    "@testing-library/react": "^11.1.1",
    "@testing-library/user-event": "^12.2.0",
    "i18next": "^19.8.3",
    "muuri": "^0.8.0",
    "muuri-react": "^3.1.6",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-i18next": "^11.7.3",
    "react-scripts": "4.0.0",
    "web-animations-js": "^2.3.2",
    "web-vitals": "^0.2.4"
  },
```

**Comment by Paol-imi** [comment]
Hi XEonAX,

This is due to a problem with React 17 which I will fix in the next release.
For now, you can try the library with React 16.

**Comment by XEonAX** [comment]
My bad, I noticed React 17 is too new. I have downgraded to React 16 and everything is fine. Great job with muuri-react.

**Comment by omeiirr** [comment]
Any updates on this?
I really like this library but am unable to use it because the rest of my project is in React 17.

**Comment by XEonAX** [comment]
@omeiirr the fix is already mentioned in my issue opening message. Or you can check the forks of this project, few forks have fixed it for react 17

**Comment by c4lliope** [comment]
@XEonAX, Hello! I am looking at your commit here;
https://github.com/XEonAX/muuri-react/commit/3466bd2432efbf40e1c6f8fea35f34938fbc3ecf

Seems like you solved the issue for React 17?

Is there a way to use your code as an NPM package, so I can keep developing on React 17?
I'm unsure on the proper way to proceed with your patch.

**Comment by XEonAX** [comment]
> 
> 
> @XEonAX, Hello! I am looking at your commit here;
> [XEonAX@3466bd2](https://github.com/XEonAX/muuri-react/commit/3466bd2432efbf40e1c6f8fea35f34938fbc3ecf)
> 
> Seems like you solved the issue for React 17?
> 
> Is there a way to use your code as an NPM package, so I can keep developing on React 17?
> I'm unsure on the proper way to proceed with your patch.

You can try `npm install XEonAX/muuri-react`. YMMV. Do note that I am not going to maintain this fork, as I stopped working on React, in pursuit of better things to do.
