### ISSUE TITLE
"Could not find a declaration file for module 'muuri-react"

### ISSUE THREAD

**Issue by pmarxbraun** [Paol-imi/muuri-react#6]
Hey there,

Trying to use "muuri-react" on my Gatsby site. 
Are you positive this is stable ?

I got this error
```
Could not find a declaration file for module 'muuri-react'. '/Users/philippebraun/Documents/Code/fehrgroup/node_modules/muuri-react/build/index.js' implicitly has an 'any' type.
  Try `npm install @types/muuri-react` if it exists or add a new declaration (.d.ts) file containing `declare module 'muuri-react';`ts(7016)
```

Beside when I `npm install @types/muuri-react`
I got this
```
MBPdePhilippe3:fehrgroup philippebraun$ npm install @types/muuri-react
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fmuuri-react - Not found
npm ERR! 404 
npm ERR! 404  '@types/muuri-react@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
```

`npm install muuri react muuri-react`

got me this

```
+ muuri@0.8.0
+ react@16.13.0
+ muuri-react@3.0.0
added 2 packages from 2 contributors, updated 1 package and audited 25903 packages in 26.607s
```

Thanks for your help

**Comment by Paol-imi** [comment]
It looks like you are using typescript in your project.
For now, this package is written only in javascript, and like all javascript packages, you can use it without problems in your typescript project.

When this package will support typescript in the future, you will find the declaration file here @ types / muuri, for now it does not exist.

You can find a detailed explanation of your problem [here](https://blog.atomist.com/declaration-file-fix/)

**Comment by pmarxbraun** [comment]
Hey @Paol-imi I made a mistake. Sorry for that. Thanks for your response anyway !
